### ISSUE TITLE
Webpack incompatability

### ISSUE THREAD

**Issue by cjbarth** [wooorm/bcp-47#18]
In these referenced line, the import doesn't include the `.json` extension, which is creating problems for Webpack. Could this be fixed? I've already tested that just adding the extension fixes the problem. If a PR is welcome, I'd be glad to make it.

https://github.com/wooorm/bcp-47/blob/ff06090fc7d703f403e9a02c61ebbbe185747a5c/lib/parse.js#L6-L7

**Comment by wooorm** [comment]
This is an issue with your WebPack config. [Here are a couple of similar issues](https://github.com/search?o=desc&q=user%3Awooorm+user%3Amicromark+user%3Aremarkjs+user%3Arehypejs+user%3Aretextjs+user%3Aunifiedjs+user%3Asyntax-tree+user%3Avfile+user%3Aget-alex+user%3Awords+webpack+require+json&s=created&type=Issues) raised with the projects I maintain, some of them contain detailed conversations about how to fix it in your config.

However, there is no downside in including the `.json` extension here, so PRs welcome!
